//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "active_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub failure_level: i32,
    pub inheritance: Option<String>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub profile_uuid: String,
    pub rule_uuid: String,
    pub prioritized_rule: Option<bool>,
    pub impacts: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
