//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "anticipated_transitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub project_uuid: String,
    pub user_uuid: String,
    pub transition: String,
    pub transition_comment: Option<String>,
    pub line: Option<i32>,
    pub message: Option<String>,
    pub line_hash: Option<String>,
    pub rule_key: String,
    pub file_path: String,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
