//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "architecture_graphs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub branch_uuid: String,
    pub ecosystem: String,
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub graph_data: String,
    pub analysis_uuid: Option<String>,
    pub perspective_key: Option<String>,
    pub graph_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
