//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ce_activity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub task_type: String,
    pub entity_uuid: Option<String>,
    pub component_uuid: Option<String>,
    pub status: String,
    pub main_is_last: bool,
    pub main_is_last_key: String,
    pub is_last: bool,
    pub is_last_key: String,
    pub submitter_uuid: Option<String>,
    pub submitted_at: i64,
    pub started_at: Option<i64>,
    pub executed_at: Option<i64>,
    pub execution_count: i32,
    pub execution_time_ms: Option<i64>,
    pub analysis_uuid: Option<String>,
    pub error_message: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_stacktrace: Option<String>,
    pub error_type: Option<String>,
    pub worker_uuid: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub node_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
