//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ce_queue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub task_type: String,
    pub entity_uuid: Option<String>,
    pub component_uuid: Option<String>,
    pub status: Option<String>,
    pub submitter_uuid: Option<String>,
    pub started_at: Option<i64>,
    pub worker_uuid: Option<String>,
    pub execution_count: i32,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
