//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "components")]
pub struct Model {
    #[sea_orm(unique)]
    pub uuid: String,
    pub kee: Option<String>,
    pub deprecated_kee: Option<String>,
    pub name: Option<String>,
    pub long_name: Option<String>,
    pub description: Option<String>,
    pub enabled: bool,
    pub scope: Option<String>,
    pub qualifier: Option<String>,
    pub private: bool,
    pub language: Option<String>,
    pub copy_component_uuid: Option<String>,
    pub path: Option<String>,
    pub uuid_path: String,
    pub branch_uuid: String,
    pub b_changed: Option<bool>,
    pub b_name: Option<String>,
    pub b_long_name: Option<String>,
    pub b_description: Option<String>,
    pub b_enabled: Option<bool>,
    pub b_qualifier: Option<String>,
    pub b_language: Option<String>,
    pub b_copy_component_uuid: Option<String>,
    pub b_path: Option<String>,
    pub b_uuid_path: Option<String>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
