//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_sources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub project_uuid: String,
    #[sea_orm(unique)]
    pub file_uuid: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub line_hashes: Option<String>,
    pub line_hashes_version: Option<i32>,
    pub data_hash: Option<String>,
    pub src_hash: Option<String>,
    pub revision: Option<String>,
    pub line_count: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub binary_data: Option<Vec<u8>>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
