//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "internal_properties")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub kee: String,
    pub is_empty: bool,
    pub text_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clob_value: Option<String>,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
