//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "issue_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub kee: Option<String>,
    pub issue_key: String,
    pub user_login: Option<String>,
    pub change_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub change_data: Option<String>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub issue_change_creation_date: Option<i64>,
    pub project_uuid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
