//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "issues_fixed")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pull_request_uuid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub issue_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
