//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "measures")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub component_uuid: String,
    pub branch_uuid: String,
    #[sea_orm(column_type = "Text")]
    pub json_value: String,
    pub json_value_hash: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
