//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    #[sea_orm(unique)]
    pub kee: String,
    pub qualifier: String,
    pub name: Option<String>,
    pub description: Option<String>,
    pub private: bool,
    pub tags: Option<String>,
    pub created_at: Option<i64>,
    pub updated_at: i64,
    pub ncloc: Option<i64>,
    pub creation_method: String,
    pub contains_ai_code: bool,
    pub ai_code_fix_enabled: bool,
    pub detected_ai_code: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
