//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_measures")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    #[sea_orm(column_type = "Decimal(Some((38, 20)))", nullable)]
    pub value: Option<Decimal>,
    pub analysis_uuid: String,
    pub component_uuid: String,
    pub text_value: Option<String>,
    pub alert_status: Option<String>,
    pub alert_text: Option<String>,
    pub person_id: Option<i32>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub measure_data: Option<Vec<u8>>,
    pub metric_uuid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
