//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_branches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub project_uuid: String,
    pub kee: String,
    pub branch_type: String,
    pub merge_branch_uuid: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub pull_request_binary: Option<Vec<u8>>,
    pub manual_baseline_analysis_uuid: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub exclude_from_purge: bool,
    pub need_issue_sync: bool,
    pub is_main: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
