//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_alm_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub alm_setting_uuid: String,
    #[sea_orm(unique)]
    pub project_uuid: String,
    pub alm_repo: Option<String>,
    pub alm_slug: Option<String>,
    pub updated_at: i64,
    pub created_at: i64,
    pub summary_comment_enabled: Option<bool>,
    pub monorepo: bool,
    pub inline_annotations_enabled: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
