//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "qprofile_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub kee: String,
    pub rules_profile_uuid: String,
    pub change_type: String,
    pub user_uuid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub change_data: Option<String>,
    pub created_at: i64,
    pub rule_change_uuid: Option<String>,
    pub sq_version: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
