//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rule_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub value: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub rule_uuid: String,
    pub is_system_tag: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
