//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rule_impact_changes")]
pub struct Model {
    pub new_software_quality: Option<String>,
    pub old_software_quality: Option<String>,
    pub new_severity: Option<String>,
    pub old_severity: Option<String>,
    pub rule_change_uuid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
