//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sca_dependencies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub sca_release_uuid: String,
    pub direct: bool,
    pub scope: String,
    pub user_dependency_file_path: Option<String>,
    pub lockfile_dependency_file_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub chains: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub production_scope: bool,
    pub is_new: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
