//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sca_issues_releases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub sca_issue_uuid: String,
    pub sca_release_uuid: String,
    pub severity: String,
    pub severity_sort_key: i32,
    pub created_at: i64,
    pub updated_at: i64,
    pub status: String,
    pub assignee_uuid: Option<String>,
    pub previous_manual_status: Option<String>,
    pub original_severity: String,
    pub manual_severity: Option<String>,
    pub show_increased_severity_warning: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
