//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sca_issue_rels_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub sca_issues_releases_uuid: String,
    pub user_uuid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub change_data: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub change_comment: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
