//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sca_analyses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    #[sea_orm(unique)]
    pub component_uuid: String,
    pub status: String,
    pub failed_reason: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub errors: String,
    #[sea_orm(column_type = "Text")]
    pub parsed_files: String,
    pub created_at: i64,
    pub updated_at: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub analysis_parameters: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
