//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sca_releases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub component_uuid: String,
    pub package_url: String,
    pub package_manager: String,
    pub package_name: String,
    pub version: String,
    pub license_expression: String,
    pub known: bool,
    pub created_at: i64,
    pub updated_at: i64,
    pub declared_license_expression: String,
    pub known_package: bool,
    pub is_new: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
