//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub root_component_uuid: String,
    pub status: String,
    pub islast: bool,
    pub version: Option<String>,
    pub build_string: Option<String>,
    pub revision: Option<String>,
    pub analysis_date: Option<i64>,
    pub period1_mode: Option<String>,
    pub period1_param: Option<String>,
    pub period1_date: Option<i64>,
    pub created_at: Option<i64>,
    pub purged: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
