//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "telemetry_metrics_sent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub metric_key: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dimension: String,
    pub last_sent: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
