//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    #[sea_orm(unique)]
    pub login: String,
    pub name: Option<String>,
    pub email: Option<String>,
    pub crypted_password: Option<String>,
    pub salt: Option<String>,
    pub hash_method: Option<String>,
    pub active: Option<bool>,
    pub external_login: String,
    pub external_identity_provider: String,
    pub external_id: String,
    pub user_local: bool,
    pub homepage_type: Option<String>,
    pub homepage_parameter: Option<String>,
    pub last_connection_date: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub reset_password: bool,
    pub last_sonarlint_connection: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
