//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub user_uuid: String,
    pub name: String,
    #[sea_orm(unique)]
    pub token_hash: String,
    pub last_connection_date: Option<i64>,
    pub created_at: i64,
    pub r#type: String,
    pub expiration_date: Option<i64>,
    pub project_uuid: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
