//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webhook_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub webhook_uuid: String,
    pub project_uuid: String,
    pub ce_task_uuid: Option<String>,
    pub analysis_uuid: Option<String>,
    pub name: String,
    pub url: String,
    pub success: bool,
    pub http_status: Option<i32>,
    pub duration_ms: i64,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_stacktrace: Option<String>,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
