version: "3.8"
services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonarcutedb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarcutedb:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonarcute-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarcutedb:
    image: postgres:18
    container_name: postgres_sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    ports:
      - 5432:5432
    networks:
      - sonarcute-network
    volumes:
      - postgresql:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:

networks:
  sonarcute-network:
    external: true
