services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonarcutedb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarcutedb:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonarcute-network
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/api/system/status | grep -q 'UP' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s

  sonarcutedb:
    image: postgres:18
    container_name: sonarcutedb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - sonarcute-network
    volumes:
      - postgresql:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:

networks:
  sonarcute-network:
    external: true
