services:
  sonarcuteapi:
    image: sonarcute-api:latest
    container_name: sonarcute-api
    networks:
      - sonarcute-network
    depends_on:
      sonarqube:
        condition: service_healthy
      sonarcutedb:
        condition: service_healthy
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DATABASE_URL: postgresql://sonar:sonar@sonarcutedb:5432/sonarcute
      SONAR_HOST_URL: http://sonarqube:9000
    ports:
      - "8888:8080"

  tokengenerator:
    image: sonarcute-token-generator:latest
    container_name: sonarcute-token-generator
    networks:
      - sonarcute-network
    depends_on:
      - sonarcuteapi
    restart: "no"
    entrypoint: >
      sh -c "
        echo ' Waiting for sonarcuteapi to be ready...' &&
        until nc -z sonarcuteapi 8080; do sleep 2; done &&
        echo ' sonarcuteapi is up! Running token generation...' &&
        /usr/local/bin/generate_tokens.sh &&
        echo ' Token generation complete.' &&
        echo ' Running quality gate setup...' &&
        /usr/local/bin/quality_gate_setup.sh &&
        echo ' Quality gate setup complete. Exiting...'
      "
    profiles:
      - init

  web:
    image: sonarcute-web:latest
    container_name: sonarcute-web
    networks:
      - sonarcute-network
    depends_on:
      - sonarcuteapi
    expose:
      - "80"
    ports:
      - "8889:80"

networks:
  sonarcute-network:
    external: true